hightrial-backend/HighTrialMain/urls.py
from django.urls import path, include
from . import views
from .views import SignUpView

app_name = 'hightrial'

urlpatterns = [
    path('',views.index, name='index'),
    path("signup/", SignUpView.as_view(), name="signup"),
    path('accounts/',include('django.contrib.auth.urls')),
    path('users/<int:owner_id>/', views.userProfile, name="profile")
]

hightrial-backend/dogs/urls.py
from django.urls import path
from . import views
from HighTrialMain import views as ht_views


app_name = 'dogs_app'

urlpatterns = [
    path('', views.dogs, name='dogs'),
    path('<int:dog_id>/', views.dog, name='dog'),
    path('breed-dogs/', views.breedDogs, name="breed-dogs"),
    path('litter/<int:dam_id>to<int:sire_id>', views.breedingResults, name="view-litter"),
    path('edit-dog/<int:dog_id>', views.editDog, name="edit-dog"),
    path('litter/<int:litter_id>', views.litter, name="litter")
]

hightrial-backend/hightrial_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from dogs import views

router = routers.DefaultRouter()
router.register('dogs', views.DogsView, 'dogs')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('HighTrialMain.urls')),
    path('dogs/', include('dogs.urls')),
    path('api/', include(router.urls))
]

hightrial-backend/dogs/models.py
from django.db import models
from django.contrib.auth.models import User

SEX_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
]

# Create your models here.

class Wallet(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    money = models.IntegerField()
    tickets = models.IntegerField()

    def __str__(self):
        return self.owner.username + "'s wallet"

class Kennel(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Litter(models.Model):
    breeder = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return " Litter #" + str(self.id) + " - " + self.breeder.username

class Dog(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    sire = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name="dogs_sire")
    dam = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name="dogs_dam")
    sex = models.CharField(max_length=10, choices=SEX_CHOICES, default='M')
    color = models.CharField(max_length=200)
    litter = models.ForeignKey(Litter, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self): 
        return self.name

class ColorGenetics(models.Model):
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE);
    kAlele = models.CharField(max_length=20, null=True, blank=True);
    aAlele = models.CharField(max_length=20, null=True, blank=True);
    eAlele = models.CharField(max_length=20, null=True, blank=True);
    bAlele = models.CharField(max_length=20, null=True, blank=True);
    dAlele = models.CharField(max_length=20, null=True, blank=True);
    sAlele = models.CharField(max_length=20, null=True, blank=True);
    mAlele = models.CharField(max_length=20, null=True, blank=True);

    def __str__(self): 
        return self.dog.name + "'s Genetics"

hightrial-backend/dogs/forms.py
from django import forms

from .models import Dog

class BreedDogForm(forms.ModelForm):
    class Meta:
        model = Dog
        fields = ('sire', 'dam')
        #maleDogs = forms.ModelChoiceField(label="Male Dogs", queryset=Dog.objects.filter(owner=this.owner, sex="M"))
        name = forms.CharField()
        date = forms.DateInput()

        #males = forms.ModelMultipleChoiceField(queryset=None)
        #females = forms.ModelMultipleChoiceField(queryset=None)

    def __init__(self, user, *args, **kwargs):
        #self.request = kwargs.pop('request')
        self.user = user;
        super(BreedDogForm, self).__init__(*args, **kwargs)
        self.fields['sire'].queryset = Dog.objects.filter(owner=self.user, sex="M")
        self.fields['dam'].queryset = Dog.objects.filter(owner=self.user, sex="F")

hightrial-backend/dogs/views.py
from django.shortcuts import render, redirect
from .models import Dog, Kennel, ColorGenetics, Wallet, Litter, User
from .forms import BreedDogForm
from django.contrib.auth.decorators import login_required
from rest_framework import viewsets
from .serializers import DogSerializer
from scripts import breedDogsScript


# Create your views here.
class DogsView(viewsets.ModelViewSet):
    serializer_class = DogSerializer
    queryset = Dog.objects.all()

@login_required
def editDog(request, dog_id):
    dog = Dog.objects.get(id=dog_id);
    context = {'dog':dog}
    return render(request, 'dogs/edit-dog.html', context)

def dogs(request):
    dogs = Dog.objects.all()
    context = {'dogs':dogs}
    return render(request, 'dogs/dogs.html', context)

def dog(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    sex = dog.sex
    puppies = []
    if (sex == "M"):
        puppies.append(Dog.objects.filter(sire=dog))
    else:
        puppies.append(Dog.objects.filter(dam=dog))
    litters = []
    litterIds = []
    if puppies:
        puppies = puppies[0]
        for puppy in puppies:
            if puppy:
                if(puppy.litter.id not in litterIds):
                    if(sex == "M"):
                        partner = puppy.dam
                    else:
                        partner = puppy.sire
                    breeder = puppy.litter.breeder
                    litterIds.append(puppy.litter.id)
                    litters.append({"id":puppy.litter.id, "partner":partner, "breeder":breeder})
    colorGenetics = ColorGenetics.objects.filter(dog=dog_id).first()
    colorGenetics = colorGenetics.__dict__
    colorString = GetColorString(colorGenetics)
    context = {'dog':dog, 'colorString': colorString, 'litters':litters}
    return render(request, 'dogs/dog.html', context)

def litter(request, litter_id):
    puppies = Dog.objects.filter(litter=litter_id)
    samplePuppy = puppies.first()
    dam = samplePuppy.dam
    sire = samplePuppy.sire
    litter = Litter.objects.get(id=litter_id)
    breeder = litter.breeder
    context = {'puppies':puppies, 'sire':sire, 'dam':dam, 'breeder':breeder}

    return render(request, 'dogs/litter.html', context)

@login_required
def breedDogs(request):
    #femaleDogs = Dog.objects.filter(sex="F")
    #maleDogs = Dog.objects.filter(sex="M")
    #context = {'maleDogs':maleDogs, 'femaleDogs': femaleDogs}
    if request.method != 'POST':
        form = BreedDogForm(user=request.user)
    else:
        form = BreedDogForm(data=request.POST, user=request.user)
        if form.is_valid():
            sire = request.POST.get('sire')
            dam = request.POST.get('dam')
            #newDog = form.save(commit=False)
            #form.save()
            return redirect('dogs_app:view-litter', sire_id=sire, dam_id=dam)
    return render(request, 'dogs/breed-dogs.html', {"form":form})


def breedingResults(request, sire_id, dam_id):
    litter = Litter.objects.create(breeder_id = request.user.id)
    sire = Dog.objects.get(id=sire_id)
    dam = Dog.objects.get(id=dam_id)
    sireDict = generateDogDict(sire)
    damDict = generateDogDict(dam)
    breedDict = getPumiDict()
    puppyList = breedDogsScript.breedDogs(damDict, sireDict, breedDict)
    for puppy in puppyList:
        puppyGenetics = puppy['genetics']['colorGenetics']
        puppyObj = Dog.objects.create(name=puppy['name'], owner=request.user, sire=sire, dam=dam, sex=puppy['sex'], color=puppy["color"],litter=litter)
        colorObj = ColorGenetics.objects.create(dog=puppyObj, kAlele=puppyGenetics['k'], aAlele=puppyGenetics['a'], eAlele=puppyGenetics['e'], bAlele=puppyGenetics['b'], dAlele=puppyGenetics['d'], sAlele=puppyGenetics['s'], mAlele=puppyGenetics['m'])
    context = {'sire':sire, 'dam':dam, 'puppyList': puppyList}
    return render(request, 'dogs/litter.html', context)

def GetColorDict(colorGenetics):
    colorDict = {}
    colorDict["k"] = colorGenetics.kAlele
    colorDict["a"]  = colorGenetics.aAlele
    colorDict["e"]  = colorGenetics.eAlele
    colorDict["b"]  = colorGenetics.bAlele
    colorDict["d"]  = colorGenetics.dAlele
    colorDict["s"]  = colorGenetics.sAlele
    colorDict["m"]  = colorGenetics.mAlele
    return colorDict

def GetColorString(colorGenetics):
    colorString = ""
    colorString += colorGenetics['kAlele'] + " "
    colorString += colorGenetics['aAlele'] + " " 
    colorString += colorGenetics['eAlele'] + " "
    colorString += colorGenetics['bAlele'] + " "
    colorString += colorGenetics['dAlele'] + " "
    colorString += colorGenetics['sAlele'] + " "
    colorString += colorGenetics['mAlele'] 
    return colorString

def generateDogDict(dog):
    dogDict = {}
    owner = dog.owner
    kennel = Kennel.objects.filter(owner=owner).first()
    genetics = ColorGenetics.objects.filter(dog=dog).first()
    dogDict['name'] = dog.name
    dogDict['kennel'] = kennel.name
    dogDict['sex'] = dog.sex
    dogDict['breed'] = "Pumi"
    dogDict['color'] = dog.color
    dogDict['genetics'] = {'colorGenetics': GetColorDict(genetics), 'traitGenetics': None}
    return dogDict;

def getPumiDict ():
    pumiDict = {
            "model": "hightrial.breed",
            "pk": 1,
            "fields": {
                "breedName": "Pumi",
                "litterMin": 2,
                "litterMax": 8,
                "colorGeneticFlags": {
                    "k": {
                        "KB": 45,
                        "ky": 50,
                        "kbr": 5
                    },
                    "a": {
                        "ay": 40,
                        "at": 50,
                        "a": 10
                    },
                    "e": {
                        "e": 20,
                        "E": 75,
                        "Em": 5
                    },
                    "b": {
                        "B": 80,
                        "b": 20
                    },
                    "d": {
                        "D": 90,
                        "d": 10
                    }
                },
                "traitGeneticFlags": None,
                "nonFoundations": {
                    "k": [
                        "kbr/kbr",
                        "kbr/ky"
                    ],
                    "b": [
                        "b/b"
                    ],
                    "d": [
                        "d/d"
                    ],
                    "joint": {
                        "k/a": {
                            "ky/ky": [
                                "at/at",
                                "a/at",
                                "at/ay"
                            ]
                        }
                    }
                },
                "phenotypeNames": {
                    "k": {
                        "ky": "seeA",
                        "kbr": "Brindle"
                    },
                    "a": {
                        "ay": "Sable",
                        "at": "Tan Points",
                        "a": "Black"
                    },
                    "e": {
                        "e": "White",
                        "Em": "Masked"
                    },
                    "b": {
                        "B": "Grey",
                        "b": "Brown"
                    },
                    "d": {
                        "D": "Grey",
                        "d": "Grey-born"
                    },
                    "m":{
                        "M": None
                    },
                    "s":{
                        "Sp": None
                    },
                    "joints": {
                        "b/d": "Lilac"
                    }
                },
                "dominanceValues": {
                    "k": [
                        "KB",
                        "kbr",
                        "ky"
                    ],
                    "a": [
                        "at",
                        "ay",
                        "a"
                    ],
                    "e": [
                        "E",
                        "Em",
                        "e"
                    ],
                    "b": [
                        "B",
                        "b"
                    ],
                    "d": [
                        "D",
                        "d"
                    ],
                    "s" : [
                        "S",
                        "sp",
                        "s"
                    ],
                    "m" : [
                        "M",
                        "m"
                    ]
                }
            }
        }
    return pumiDict

hightrial-backend/dogs/templates/dogs/base.html
{% load django_bootstrap5 %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1,
   shrink-to-fit=no">
   <title>High Trial</title>
   {% bootstrap_css %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
 
        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'hightrial:index'%}">
                        Home</a>
                 </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dogs_app:dogs'%}">
                        Explore Dogs</a>
                 </li>
                 <li>
                    <a class="nav-link" href="{% url 'dogs_app:breed-dogs'%}">
                        Breed</a>
                 </li>
            </ul>
        </div>
        <span class="navbar-text">
            {% if user.is_authenticated %}
                Hi, <a href="{% url 'hightrial:profile' user.id %}">{{ user.username }}</a>! 
            {% else %}
                <p>You are not logged in</p>
                <a href="{% url 'hightrial:login' %}">Log In</a>  |  <a href="/signup'">Sign Up</a>  
            {% endif %}
        </span>
    </nav>
   <main role="main" class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %} {% endblock page_header %}
    </div>
       <div>
           {% block content %}{% endblock content %}
       </div>
   </main>
</body>
</html>

hightrial-backend/dogs/templates/dogs/breed-dogs.html
{% extends 'dogs/base.html' %}
{% load static %}

{% block content %}
    <h3>Breed Dogs</h3>
    <p>Select which two dogs you would like to breed.</p>
    <br>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

hightrial-backend/dogs/templates/dogs/dog.html
{% extends 'dogs/base.html' %}
{% load static %}

{% block page_header %}
    <h3>{{ dog.name }}</h3>
    <small> <a href="{% url 'dogs_app:edit-dog' dog.id %}">edit dog</a></small>
{% endblock page_header %}
{% block content %}
<div>
    <p><b>Sex: </b>{{dog.sex}}</p>
    <p><b>Color: </b>{{dog.color}}</p>
    <p><b>Genetics: </b>{{colorString}}</p>
</div>
<h5>Litters</h5>
<div class="row">
    {% for litter in litters %}
        <div class="col-md-3 " style="margin-bottom:10px;">
            <div class="card h-100">
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{% url 'dogs_app:litter' litter.id %}">Litter #{{ litter.id }} with {{litter.partner.name}}</a>
                    </h4>
                    <div class="card-subtitle">
                        Bred By: <a href="{% url 'hightrial:profile' litter.breeder.id %}">{{ litter.breeder.username }}</a>
                    </div>
                </div>
            </div>
        </div>
    {% empty %}
        <p>This dog has not had any litters yet.</p>
    {% endfor %}
</div>
    
{% endblock content %}

hightrial-backend/dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load static %}

{% block content %}
    <h4>Dogs</h4>
    <div class="row">
        {% for dog in dogs %}
            <div class="col-md-3 " style="margin-bottom:10px;">
                <div class="card h-100">
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{% url 'dogs_app:dog' dog.id %}">{{ dog.name }}</a>
                        </h4>
                        <div class="card-subtitle">
                            Owned By: <a href="{% url 'hightrial:profile' dog.owner.id %}">{{ dog.owner }}</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>There are no dogs in the system yet.</p>
        {% endfor %}
    </div>
{% endblock content %}

hightrial-backend/dogs/templates/dogs/edit-dog.html
{% extends 'dogs/base.html' %}
{% load static %}

{% block content %}
{% endblock content %}

hightrial-backend/dogs/templates/dogs/litter.html
{% extends 'dogs/base.html' %}
{% load static %}

{% block content %}
    <h5><a href="{% url 'dogs_app:dog' dam.id %}">{{dam.name}}</a> x <a href="{% url 'dogs_app:dog' sire.id %}">{{sire.name}}</a></h5>
    <b>Bred By: <a href="{% url 'hightrial:profile' breeder.id %}">{{ breeder.username }}</a></b>
    <br>
    <br>
    <div class="row">
        {% for puppy in puppies %}
            <div class="col-md-3 " style="margin-bottom:10px;">
                <div class="card h-100">
                    <div class="card-body">
                        <h4 class="card-title">
                           <a href="{% url 'dogs_app:dog' puppy.id %}">{{ puppy.name }}</a>
                        </h4>
                        <div class="card-subtitle">
                            Breed: {{puppy.breed}}
                        </div>
                        <p class="card-text">
                            Sex: {{puppy.sex}}
                            <br>
                            Color: {{puppy.color}}
                        </p>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>This litter does not exist</p>
        {% endfor %}
    </div>
    
{% endblock content %}